config/routes.rb
Rails.application.routes.draw do
  get 'charts/index'
  devise_for :nguoidungs
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
    end

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  resources :loais
   get '/' => 'home#index'
  get '/contact' => 'contact#contact'
   get '/home' => 'home#index'

  get '/mottrieubatrieu' => 'mottrieubatrieu#index'
  
  get '/dienthoai' => 'mottrieubatrieu#tatcasp'
  get 'theogia/giacoban' => 'mottrieubatrieu#gia1'
  get 'theogia/motba' => 'mottrieubatrieu#motba'
  get 'theogia/batam' => 'mottrieubatrieu#batam'
  get 'theogia/tammuoi' => 'mottrieubatrieu#tammuoi'
  get 'theogia/muoimuoilam' => 'mottrieubatrieu#muoimuoilam'
  get 'theogia/muoilamhaimuoi' => 'mottrieubatrieu#muoilamhaimuoi'
  
  get 'theogia/haimuoihailam' => 'mottrieubatrieu#haimuoihailam'
  get 'theogia/hailambamuoi' => 'mottrieubatrieu#hailambamuoi'
  get 'theogia/bamuoibalam' => 'mottrieubatrieu#bamuoibalam'
  get 'theogia/balambonmuoi' => 'mottrieubatrieu#balambonmuoi'
  get 'theogia/bonmuoibonlam' => 'mottrieubatrieu#bonmuoibonlam'
  get 'theogia/bonlamnammuoi' => 'mottrieubatrieu#bonlamnammuoi'


  get '/phukien' => 'giaphukien#index'

  get 'theogia/gia_0_2' => 'giaphukien#gia_0_2' 
  get 'theogia/gia_2_4' => 'giaphukien#gia_2_4'
  get 'theogia/gia_4_6' => 'giaphukien#gia_4_6'
  get 'theogia/gia_6_8' => 'giaphukien#gia_6_8'
  get 'theogia/gia_8_10' => 'giaphukien#gia_8_10'
  
  get 'theogia/gia_10_12' => 'giaphukien#gia_10_12'
  get 'theogia/gia_12_14' => 'giaphukien#gia_12_14'
  get 'theogia/gia_14_16' => 'giaphukien#gia_14_16'
  get 'theogia/gia_16_18' => 'giaphukien#gia_16_18'
  get 'theogia/gia_18_20' => 'giaphukien#gia_18_20'
  get 'theogia/gia_20' => 'giaphukien#gia_20'
  resources :products do
  get :who_bought, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'home#index'
end

app/models/cart.rb
class Cart < ApplicationRecord
	has_many :line_items, :dependent => :destroy
    $total
    
	 def add_product(product_id)
        current_item = line_items.find_by_product_id(product_id)
        if current_item 
            current_item.quantity += 1
        else
            current_item = line_items.build(:product_id => product_id)
        end
        current_item
    end

    def total_price 
        line_items.to_a.sum { |item| item.total_price }
        $total = line_items.to_a.sum { |item| item.total_price }
    end
    def self.total
        return $total
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  #skip_before_action :authorize
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :authenticate_nguoidung!, except: [:show, :index,:destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = []
    if session[:cart_id] != nil
      @carts << Cart.find_by_id(session[:cart_id])
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
      @cart = current_cart
      @cart.destroy
      session[:cart_id] = nil

      respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_index_url, notice: 'Invalid cart'
      end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<% unless cart.line_items.empty? %>
<h2>Đơn hàng của bạn</h2>
	<table class="table table-bordered">
		<th>Số lượng</th>
		<th>Tên sản phẩm</th>
		<th>Giá sản phẩm</th>
		<%= render(cart.line_items) %>
		<tr class="total_line">
			<b><p style="font-size: 15px;">Tổng đơn:</p></b>
			<p style="font-size: 20px;" class="total_cell"><%= number_to_currency(cart.total_price, unit: " VNĐ",format: "%n %u",:precision => 0) %></p><hr>
		</tr>
	</table>
	<%= button_to "Đặt hàng", new_order_path, method: :get %>
	<%= button_to 'Xoá giỏ hàng', cart, method: :delete,data: { confirm: 'Are you sure?' } %>
	<% end %>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/carts/new.html.erb
<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<!-- <h2>Your Cart</h2>
<table>
    <% @cart.line_items.each do |item| %>
        <tr>
            <td><%= item.quantity %> x </td>
            <td><%= item.product.title %></td>
            <td class="item_price"><%= number_to_currency(item.total_price) %></td>
        </tr>
    <% end %>
     
    <tr class="total_line">
        <td colspan="2">Total</td>
        <td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
    </tr>
</table>

<%= button_to 'Empty cart', 
              @cart, 
              :method => :delete,
              data: {:confirm => 'Are you sure?'} %>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>
 -->

<p id="notice"><%= notice %></p>  
 <%= render @cart %>