config/routes.rb
Rails.application.routes.draw do
  get 'charts/index'
  devise_for :nguoidungs
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
    end

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  resources :loais
   get '/' => 'home#index'
  get '/contact' => 'contact#contact'
   get '/home' => 'home#index'

  get '/mottrieubatrieu' => 'mottrieubatrieu#index'
  
  get '/dienthoai' => 'mottrieubatrieu#tatcasp'
  get 'theogia/giacoban' => 'mottrieubatrieu#gia1'
  get 'theogia/motba' => 'mottrieubatrieu#motba'
  get 'theogia/batam' => 'mottrieubatrieu#batam'
  get 'theogia/tammuoi' => 'mottrieubatrieu#tammuoi'
  get 'theogia/muoimuoilam' => 'mottrieubatrieu#muoimuoilam'
  get 'theogia/muoilamhaimuoi' => 'mottrieubatrieu#muoilamhaimuoi'
  
  get 'theogia/haimuoihailam' => 'mottrieubatrieu#haimuoihailam'
  get 'theogia/hailambamuoi' => 'mottrieubatrieu#hailambamuoi'
  get 'theogia/bamuoibalam' => 'mottrieubatrieu#bamuoibalam'
  get 'theogia/balambonmuoi' => 'mottrieubatrieu#balambonmuoi'
  get 'theogia/bonmuoibonlam' => 'mottrieubatrieu#bonmuoibonlam'
  get 'theogia/bonlamnammuoi' => 'mottrieubatrieu#bonlamnammuoi'


  get '/phukien' => 'giaphukien#index'

  get 'theogia/gia_0_2' => 'giaphukien#gia_0_2' 
  get 'theogia/gia_2_4' => 'giaphukien#gia_2_4'
  get 'theogia/gia_4_6' => 'giaphukien#gia_4_6'
  get 'theogia/gia_6_8' => 'giaphukien#gia_6_8'
  get 'theogia/gia_8_10' => 'giaphukien#gia_8_10'
  
  get 'theogia/gia_10_12' => 'giaphukien#gia_10_12'
  get 'theogia/gia_12_14' => 'giaphukien#gia_12_14'
  get 'theogia/gia_14_16' => 'giaphukien#gia_14_16'
  get 'theogia/gia_16_18' => 'giaphukien#gia_16_18'
  get 'theogia/gia_18_20' => 'giaphukien#gia_18_20'
  get 'theogia/gia_20' => 'giaphukien#gia_20'
  resources :products do
  get :who_bought, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'home#index'
end

app/models/product.rb
class Product < ApplicationRecord
    has_attached_file :image, styles: {medium: "10000x10000>", thumb: "10000x10000>"}, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    include PgSearch
    pg_search_scope :search_name, against: [:title, :description],   using: {
        tsearch: {
          prefix: true,
        },
      }
    belongs_to :loai

    validates :title, :description,:image,:price, presence: true
    validates :price, numericality: {greater_than_or_equal_to: 0.01}

    has_many :line_items
    has_many :orders, through: :line_items
    before_destroy :check_if_has_line_item
  
	private
  
    def check_if_has_line_item
        if line_items.empty?
            return true
        else
            errors.add(:base, 'This product has a LineItem')
            return false
        end
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include CurrentCart
  before_action :set_cart
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  #skip_before_action :authorize, only: [:show]
  before_action :authenticate_nguoidung!, only: [:index, :create, :edit ,:update, :destroy]

  # GET /products
  # GET /products.json

  def index
    if params[:query].present?
      @products = Product.search_name(params[:query]).paginate(page: params[:page], per_page: 10)
    else
      @products = Product.all.paginate(page: params[:page], per_page: 10)
    end

  end

  # GET /products/1
  # GET /products/1.json
  def show
    @ecs = Product.limit(3).order("RANDOM()")
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price, :species, :image, :loai_id, :hot)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product, html: { multipart: true } do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= tinymce %>


  <div class="field">
 <div class="input-group input-group-lg">
  <span class="input-group-addon" id="sizing-addon1">Name:</span>
    <%= form.text_field :title ,:class=>'form-control'%>

  </div>
  </div>


  <div class="field">
<div class="input-group input-group-lg">
  <span class="input-group-addon" id="sizing-addon1">Content:</span>    
  <%= form.text_area :description, :class => "tinymce", :rows => 10, :cols => 20 %>

  <%# <%= form.text_area :description ,:class=>'form-control' %> 
  </div>

  <div class="field">
<div class="input-group input-group-lg">
  <span class="input-group-addon" id="sizing-addon1">image:</span>  
    <%= form.file_field :image %>

  </div>

  <div class="field">
<div class="input-group input-group-lg">
  <span class="input-group-addon" id="sizing-addon1">Price:</span>
      <%= form.text_field :price,:class=>'form-control' %>
      </div>
  </div>

  <div class="field">
      <div class="input-group input-group-lg">
      <span class="input-group-addon" id="sizing-addon1">Type:</span>
       <%= form.select :loai_id, options_from_collection_for_select(Loai.all, :id, :loaihang), {:include_blank => '----'}, :class=>'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag products_path, method: :get do %>
  <%= text_field_tag "query", params[:query], placeholder: "Title" %>
  <%= submit_tag "Search!" %>
<% end %>



<h1>Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Price</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><b><%= product.title %></b></td>
        <td><%= product.description %></td>
        <td><%= image_tag product.image.url(:medium),:size=>"80x80"%></td>
        <td><%= product.price %></td>
        <td><%= product.loai.loaihang %></td>

        

        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p><%= will_paginate @products %></p>
<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% content_for :title, @product.title + " | Cửa hàng Samsung" %>

<p id="notice"><%= notice %></p>
<div class="single">
	<div class="container">
		<div class="col-md-6 single-right-left animated wow slideInUp animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: slideInUp;">
			<div class="grid images_3_of_2">
				
<div class="zoom"><center><p><%= image_tag @product.image.url(:medium),:style=>"width:100%; height:auto; max-width: 60%; max-height:60%"%></p></center></div>

					<div class="clearfix"></div>
			</div>
		</div>
		<div class="col-md-6 single-right-left simpleCart_shelfItem animated wow slideInRight animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: slideInRight;">
					<a class="list-group-item"><span class="badge badge-primary">Thông tin sản phẩm</span> <i class="ti ti-bell"></i> 
						<h1 style="font-size: 23px; font-weight:bold"><%= @product.title %></h1>
						<span style="font-size: 30px;color:#BF360C" class="item_price"><%= number_to_currency(@product.price, unit: " VNĐ",format: "%n %u",:precision => 0) %></span>		
					</a>
					<a class="list-group-item">
						<span class="badge badge-info">Loại</span> <i class="ti ti-bell"></i> <%= @product.loai.loaihang %> 
						<iframe src="https://www.facebook.com/plugins/share_button.php?href= <%= request.original_url %> " width="113" height="20" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>
					</a>
 
					<%= image_tag "/assets/banner2.gif",:style=>"height: auto ;width: 100%; z-index: 1" %>	
					<div class="description">
						<%= button_to 'Thêm vào giỏ hàng', line_items_path(:product_id => @product),remote: true, :class=>"item_add single-item hvr-outline-out button2" %>
						<!-- Hiển thị random 5 phụ kiện -->
							<% @ecs.each do |product| %>				
							<div class="col-md-4 product-men">
							<% if product.hot == true %>
								<%= image_tag "/assets/hot.gif",:style=>"position: absolute;height: 50px ;width: 80px; left: 0px; z-index: 1" %>
							<% end %>
							<div class="men-pro-item simpleCart_shelfItem">
								<div class="men-thumb-item">
								<p><%= image_tag product.image.url(:medium), :class=>"pro-image-front", :style=>"width: 100%;height: auto" %></p>
								<p><%= image_tag product.image.url(:medium), :class=>"pro-image-back", :style=>"width: 100%;height: auto"%></p>
										<div class="men-cart-pro">
											<div class="inner-men-cart-pro">
											        <td><%= link_to 'Chi tiết', product ,:class=>"link-product-add-cart",:style=>"width:100%;margin-bottom:50px" %></td>
											</div>
										</div>										
								</div>
								<div class="item-info-product ">
								<%=link_to product do%><h3 style="font-size:15px"><%= product.title %></h3> <%end%>									
								<div class="info-product-price">
								<span  style="font-size:15px" class="item_price"><%= number_to_currency(product.price, unit: " VNĐ",format: "%n %u",:precision => 0) %></span>
									</div>
									<%= button_to 'Thêm vào giỏ hàng', line_items_path(:product_id => product),remote: true, :class=>"item_add single-item hvr-outline-out button2", :style=>"width:auto;font-size:13px" %>
								</div>
							</div>
							</div>
    						<% end %>
						</div>
						<!--Hết phần hiển thị random phụ kiện-->

					</a> </center>

						<div class="clearfix"> </div>
					</div>				
		</div>


				
						<div class="clearfix"></div>
</div>


			<div class="alert alert-success alert-dismissable">
				<button aria-hidden="true" data-dismiss="alert" class="close" type="button"> Đóng </button>
				<h2 class="t-button"><span class="label label-success">Chính sách ưu đãi khi mua hàng</span></h2>
				<p> <%= image_tag "/assets/delivery.png", :size=>"30x23" %> Miễn phí vận chuyển</p>
				<p> <%= image_tag "/assets/doitra.png", :size=>"30x23" %> Cho phép đổi trả trong 2 tháng đầu tiên</p>
				<p> <%= image_tag "/assets/247.png", :size=>"30x23" %> Dịch vụ khách hàng 24/7</p>
			</div>


				<div class="clearfix"> </div>
				<div class="bootstrap-tab animated wow slideInUp animated" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: slideInUp;">
					<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
						<ul id="myTab" class="nav nav-tabs" role="tablist">
							<li role="presentation" class="active"><a href="#home" id="home-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">Chi tiết sản phẩm</a></li>
							<li role="presentation"><a href="#profile" role="tab" id="profile-tab" data-toggle="tab" aria-controls="profile">Đánh giá sản phẩm</a></li>
						</ul>
						<div style="padding-left:5%; padding-right:5%" id="myTabContent" class="tab-content">
							<div role="tabpanel" class="tab-pane fade in active bootstrap-tab-text" id="home" aria-labelledby="home-tab">
								<h5>  <%= @product.title %></h5>
						  				<%=raw @product.description %>
  				</div>
							<div role="tabpanel" class="tab-pane fade bootstrap-tab-text" id="profile" aria-labelledby="profile-tab">
								<div class="bootstrap-tab-text-grids">
									<div class="bootstrap-tab-text-grid">
										
										<div id="disqus_thread"></div>
											<script>
											(function() {
											var d = document, s = d.createElement('script');
											s.src = 'https://bansamsung.disqus.com/embed.js';
											s.setAttribute('data-timestamp', +new Date());
											(d.head || d.body).appendChild(s);
											})();
											</script>
											<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>		
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

<% if session[:user_id] %>
<p>Chức năng cho Admin</p>
<%= link_to 'Sửa thông tin sản phẩm', edit_product_path(@product) %> |
<%= link_to 'Quản lý sản phẩm', products_path %>
<% end %>